//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanNuocUong_TheCoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDONHANGs = new HashSet<CTDONHANG>();
        }
    
        public string MADH { get; set; }
        public string MAKM { get; set; }
        public int MATT { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> THOIGIANGIAOHANG { get; set; }
        public Nullable<byte> DANHGIA { get; set; }
        public string NHANXET { get; set; }
        public decimal TAMTINH { get; set; }
        public Nullable<int> TRUDIEMTINHLUY { get; set; }
        public Nullable<decimal> SOTIENGIAMKM { get; set; }
        public decimal TONGITEN { get; set; }
        public string SOTK { get; set; }
        public string TENPTTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual PTTHANHTOAN PTTHANHTOAN { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
