//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanNuocUong_TheCoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPTTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIPTTT()
        {
            this.PTTHANHTOANs = new HashSet<PTTHANHTOAN>();
        }
    
        public string MALOAIPTTT { get; set; }
        public string TENLOAIPTTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTTHANHTOAN> PTTHANHTOANs { get; set; }
    }
}
