//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanNuocUong_TheCoffeeShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class thecoffeeshopEntities : DbContext
    {
        public thecoffeeshopEntities()
            : base("name=thecoffeeshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDONHANG> CTDONHANGs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAIPTTT> LOAIPTTTs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<PTTHANHTOAN> PTTHANHTOANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    
        public virtual ObjectResult<sp_ChiTietSanPham_Result> sp_ChiTietSanPham(string ten_sp)
        {
            var ten_spParameter = ten_sp != null ?
                new ObjectParameter("ten_sp", ten_sp) :
                new ObjectParameter("ten_sp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietSanPham_Result>("sp_ChiTietSanPham", ten_spParameter);
        }
    
        public virtual int sp_ChuyenMaLoai(string ten_loai, ObjectParameter ma_loai)
        {
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenMaLoai", ten_loaiParameter, ma_loai);
        }
    
        public virtual ObjectResult<sp_DanhSachSanPham_Result> sp_DanhSachSanPham(string ten_loai)
        {
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSanPham_Result>("sp_DanhSachSanPham", ten_loaiParameter);
        }
    
        public virtual int sp_taoMaNV(Nullable<int> dem, ObjectParameter ma)
        {
            var demParameter = dem.HasValue ?
                new ObjectParameter("dem", dem) :
                new ObjectParameter("dem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_taoMaNV", demParameter, ma);
        }
    
        public virtual int sp_TaoMaSanPham(string ma_loai, Nullable<int> dem, ObjectParameter ma)
        {
            var ma_loaiParameter = ma_loai != null ?
                new ObjectParameter("ma_loai", ma_loai) :
                new ObjectParameter("ma_loai", typeof(string));
    
            var demParameter = dem.HasValue ?
                new ObjectParameter("dem", dem) :
                new ObjectParameter("dem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoMaSanPham", ma_loaiParameter, demParameter, ma);
        }
    
        public virtual int sp_ThemNVQuanTri(string hoTen, Nullable<System.DateTime> ngaySinh, string diaChi, string diaChi2, string sdt, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var diaChi2Parameter = diaChi2 != null ?
                new ObjectParameter("diaChi2", diaChi2) :
                new ObjectParameter("diaChi2", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNVQuanTri", hoTenParameter, ngaySinhParameter, diaChiParameter, diaChi2Parameter, sdtParameter, emailParameter);
        }
    
        public virtual int sp_ThemTaiKhoanNV(string ma, string sdt)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoanNV", maParameter, sdtParameter);
        }
    }
}
