

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanNuocUong_TheCoffeeShop.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class thecoffeeshopEntities : DbContext
{
    public thecoffeeshopEntities()
        : base("name=thecoffeeshopEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CTDONHANG> CTDONHANGs { get; set; }

    public virtual DbSet<DONHANG> DONHANGs { get; set; }

    public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }

    public virtual DbSet<LOAIPTTT> LOAIPTTTs { get; set; }

    public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }

    public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }

    public virtual DbSet<PTTHANHTOAN> PTTHANHTOANs { get; set; }

    public virtual DbSet<SANPHAM> SANPHAMs { get; set; }

    public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }

    public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }


    public virtual ObjectResult<sp_DanhSachSanPham_Result> sp_DanhSachSanPham(string ten_loai)
    {

        var ten_loaiParameter = ten_loai != null ?
            new ObjectParameter("ten_loai", ten_loai) :
            new ObjectParameter("ten_loai", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSanPham_Result>("sp_DanhSachSanPham", ten_loaiParameter);
    }


    public virtual int sp_TaoMaSanPham(string ma_loai, Nullable<int> dem, ObjectParameter ma)
    {

        var ma_loaiParameter = ma_loai != null ?
            new ObjectParameter("ma_loai", ma_loai) :
            new ObjectParameter("ma_loai", typeof(string));


        var demParameter = dem.HasValue ?
            new ObjectParameter("dem", dem) :
            new ObjectParameter("dem", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoMaSanPham", ma_loaiParameter, demParameter, ma);
    }


    public virtual int sp_ThemSanPham(string ten_sp, Nullable<decimal> gia_sp, string anh_sp, Nullable<int> soluong, string ma_loai)
    {

        var ten_spParameter = ten_sp != null ?
            new ObjectParameter("ten_sp", ten_sp) :
            new ObjectParameter("ten_sp", typeof(string));


        var gia_spParameter = gia_sp.HasValue ?
            new ObjectParameter("gia_sp", gia_sp) :
            new ObjectParameter("gia_sp", typeof(decimal));


        var anh_spParameter = anh_sp != null ?
            new ObjectParameter("anh_sp", anh_sp) :
            new ObjectParameter("anh_sp", typeof(string));


        var soluongParameter = soluong.HasValue ?
            new ObjectParameter("soluong", soluong) :
            new ObjectParameter("soluong", typeof(int));


        var ma_loaiParameter = ma_loai != null ?
            new ObjectParameter("ma_loai", ma_loai) :
            new ObjectParameter("ma_loai", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", ten_spParameter, gia_spParameter, anh_spParameter, soluongParameter, ma_loaiParameter);
    }


    public virtual int sp_ChuyenMaLoai(string ten_loai, ObjectParameter ma_loai)
    {

        var ten_loaiParameter = ten_loai != null ?
            new ObjectParameter("ten_loai", ten_loai) :
            new ObjectParameter("ten_loai", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenMaLoai", ten_loaiParameter, ma_loai);
    }


    public virtual ObjectResult<sp_ChiTietSanPham_Result> sp_ChiTietSanPham(string ten_sp)
    {

        var ten_spParameter = ten_sp != null ?
            new ObjectParameter("ten_sp", ten_sp) :
            new ObjectParameter("ten_sp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietSanPham_Result>("sp_ChiTietSanPham", ten_spParameter);
    }


    public virtual ObjectResult<sp_XemKhuyenMai_Result> sp_XemKhuyenMai()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemKhuyenMai_Result>("sp_XemKhuyenMai");
    }


    public virtual int sp_CapNhatNguoiDung(string userid, string phanquyen, ObjectParameter hoten, ObjectParameter sdt, ObjectParameter diachi, ObjectParameter ngaysinh, ObjectParameter email, ObjectParameter diachi2)
    {

        var useridParameter = userid != null ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(string));


        var phanquyenParameter = phanquyen != null ?
            new ObjectParameter("phanquyen", phanquyen) :
            new ObjectParameter("phanquyen", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatNguoiDung", useridParameter, phanquyenParameter, hoten, sdt, diachi, ngaysinh, email, diachi2);
    }


    public virtual int sp_DoiMatKhau(string userid, string phanquyen, ObjectParameter userpassword, string confirm_password)
    {

        var useridParameter = userid != null ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(string));


        var phanquyenParameter = phanquyen != null ?
            new ObjectParameter("phanquyen", phanquyen) :
            new ObjectParameter("phanquyen", typeof(string));


        var confirm_passwordParameter = confirm_password != null ?
            new ObjectParameter("confirm_password", confirm_password) :
            new ObjectParameter("confirm_password", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiMatKhau", useridParameter, phanquyenParameter, userpassword, confirm_passwordParameter);
    }

}

}

