//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanNuocUong_TheCoffeeShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class thecoffeeshopEntities : DbContext
    {
        public thecoffeeshopEntities()
            : base("name=thecoffeeshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDONHANG> CTDONHANGs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAIPTTT> LOAIPTTTs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<PTTHANHTOAN> PTTHANHTOANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    
        public virtual ObjectResult<sp_ChiTietSanPham_Result> sp_ChiTietSanPham(string ten_sp)
        {
            var ten_spParameter = ten_sp != null ?
                new ObjectParameter("ten_sp", ten_sp) :
                new ObjectParameter("ten_sp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietSanPham_Result>("sp_ChiTietSanPham", ten_spParameter);
        }
    
        public virtual int sp_ChuyenMaLoai(string ten_loai, ObjectParameter ma_loai)
        {
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenMaLoai", ten_loaiParameter, ma_loai);
        }
    
        public virtual ObjectResult<sp_DanhSachSanPham_Result> sp_DanhSachSanPham(string ten_loai)
        {
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSanPham_Result>("sp_DanhSachSanPham", ten_loaiParameter);
        }
    
        public virtual int sp_taoMaNV(Nullable<int> dem, ObjectParameter ma)
        {
            var demParameter = dem.HasValue ?
                new ObjectParameter("dem", dem) :
                new ObjectParameter("dem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_taoMaNV", demParameter, ma);
        }
    
        public virtual int sp_TaoMaSanPham(string ma_loai, Nullable<int> dem, ObjectParameter ma)
        {
            var ma_loaiParameter = ma_loai != null ?
                new ObjectParameter("ma_loai", ma_loai) :
                new ObjectParameter("ma_loai", typeof(string));
    
            var demParameter = dem.HasValue ?
                new ObjectParameter("dem", dem) :
                new ObjectParameter("dem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoMaSanPham", ma_loaiParameter, demParameter, ma);
        }
    
        public virtual int sp_ThemNVQuanTri(string hoTen, Nullable<System.DateTime> ngaySinh, string diaChi, string diaChi2, string sdt, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var diaChi2Parameter = diaChi2 != null ?
                new ObjectParameter("diaChi2", diaChi2) :
                new ObjectParameter("diaChi2", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNVQuanTri", hoTenParameter, ngaySinhParameter, diaChiParameter, diaChi2Parameter, sdtParameter, emailParameter);
        }
    
        public virtual int sp_ThemTaiKhoanNV(string ma, string sdt)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoanNV", maParameter, sdtParameter);
        }
    
        public virtual int sp_CapNhatThongTinCaNhanNV(string ma_nd, string hoten, string sdt, string diachi, Nullable<System.DateTime> ngaysinh, string diachi2, string email)
        {
            var ma_ndParameter = ma_nd != null ?
                new ObjectParameter("ma_nd", ma_nd) :
                new ObjectParameter("ma_nd", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var diachi2Parameter = diachi2 != null ?
                new ObjectParameter("diachi2", diachi2) :
                new ObjectParameter("diachi2", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinCaNhanNV", ma_ndParameter, hotenParameter, sdtParameter, diachiParameter, ngaysinhParameter, diachi2Parameter, emailParameter);
        }
    
        public virtual int sp_ChinhSuaSanPham(string ma_sp, string ten_sp, Nullable<decimal> gia_sp, string anh_sp, Nullable<int> soluong, string mo_ta, string ma_loai)
        {
            var ma_spParameter = ma_sp != null ?
                new ObjectParameter("ma_sp", ma_sp) :
                new ObjectParameter("ma_sp", typeof(string));
    
            var ten_spParameter = ten_sp != null ?
                new ObjectParameter("ten_sp", ten_sp) :
                new ObjectParameter("ten_sp", typeof(string));
    
            var gia_spParameter = gia_sp.HasValue ?
                new ObjectParameter("gia_sp", gia_sp) :
                new ObjectParameter("gia_sp", typeof(decimal));
    
            var anh_spParameter = anh_sp != null ?
                new ObjectParameter("anh_sp", anh_sp) :
                new ObjectParameter("anh_sp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var mo_taParameter = mo_ta != null ?
                new ObjectParameter("mo_ta", mo_ta) :
                new ObjectParameter("mo_ta", typeof(string));
    
            var ma_loaiParameter = ma_loai != null ?
                new ObjectParameter("ma_loai", ma_loai) :
                new ObjectParameter("ma_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaSanPham", ma_spParameter, ten_spParameter, gia_spParameter, anh_spParameter, soluongParameter, mo_taParameter, ma_loaiParameter);
        }
    
        public virtual int sp_ThayDoiTrangThaiSanPham(string ma_sp)
        {
            var ma_spParameter = ma_sp != null ?
                new ObjectParameter("ma_sp", ma_sp) :
                new ObjectParameter("ma_sp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThayDoiTrangThaiSanPham", ma_spParameter);
        }
    
        public virtual int sp_ThemLoaiSanPham(string ma_loai, string ten_loai)
        {
            var ma_loaiParameter = ma_loai != null ?
                new ObjectParameter("ma_loai", ma_loai) :
                new ObjectParameter("ma_loai", typeof(string));
    
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiSanPham", ma_loaiParameter, ten_loaiParameter);
        }
    
        public virtual int sp_ThemSanPham(string ten_sp, Nullable<decimal> gia_sp, string anh_sp, Nullable<int> soluong, string ma_loai, string mo_ta)
        {
            var ten_spParameter = ten_sp != null ?
                new ObjectParameter("ten_sp", ten_sp) :
                new ObjectParameter("ten_sp", typeof(string));
    
            var gia_spParameter = gia_sp.HasValue ?
                new ObjectParameter("gia_sp", gia_sp) :
                new ObjectParameter("gia_sp", typeof(decimal));
    
            var anh_spParameter = anh_sp != null ?
                new ObjectParameter("anh_sp", anh_sp) :
                new ObjectParameter("anh_sp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var ma_loaiParameter = ma_loai != null ?
                new ObjectParameter("ma_loai", ma_loai) :
                new ObjectParameter("ma_loai", typeof(string));
    
            var mo_taParameter = mo_ta != null ?
                new ObjectParameter("mo_ta", mo_ta) :
                new ObjectParameter("mo_ta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", ten_spParameter, gia_spParameter, anh_spParameter, soluongParameter, ma_loaiParameter, mo_taParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemSanPham_Result> sp_TimKiemSanPham(string search_string)
        {
            var search_stringParameter = search_string != null ?
                new ObjectParameter("search_string", search_string) :
                new ObjectParameter("search_string", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemSanPham_Result>("sp_TimKiemSanPham", search_stringParameter);
        }
    
        public virtual ObjectResult<sp_HienThiDanhSachLoaiSanPham_Result> sp_HienThiDanhSachLoaiSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiDanhSachLoaiSanPham_Result>("sp_HienThiDanhSachLoaiSanPham");
        }
    
        public virtual ObjectResult<sp_DanhSachCTDonHang_Result> sp_DanhSachCTDonHang(string ma_dh)
        {
            var ma_dhParameter = ma_dh != null ?
                new ObjectParameter("ma_dh", ma_dh) :
                new ObjectParameter("ma_dh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachCTDonHang_Result>("sp_DanhSachCTDonHang", ma_dhParameter);
        }
    
        public virtual ObjectResult<sp_HienThiDanhSachDonHang_Result> sp_HienThiDanhSachDonHang(string tinh_trang)
        {
            var tinh_trangParameter = tinh_trang != null ?
                new ObjectParameter("tinh_trang", tinh_trang) :
                new ObjectParameter("tinh_trang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiDanhSachDonHang_Result>("sp_HienThiDanhSachDonHang", tinh_trangParameter);
        }
    
        public virtual ObjectResult<sp_ThongTinDonHang_Result> sp_ThongTinDonHang(string ma_dh)
        {
            var ma_dhParameter = ma_dh != null ?
                new ObjectParameter("ma_dh", ma_dh) :
                new ObjectParameter("ma_dh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongTinDonHang_Result>("sp_ThongTinDonHang", ma_dhParameter);
        }
    
        public virtual ObjectResult<sp_XemKhuyenMai_Result> sp_XemKhuyenMai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemKhuyenMai_Result>("sp_XemKhuyenMai");
        }
    
        public virtual ObjectResult<sp_ThongKeTheoNgay_Result> sp_ThongKeTheoNgay(Nullable<System.DateTime> ngay, Nullable<System.DateTime> ngay2)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var ngay2Parameter = ngay2.HasValue ?
                new ObjectParameter("ngay2", ngay2) :
                new ObjectParameter("ngay2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeTheoNgay_Result>("sp_ThongKeTheoNgay", ngayParameter, ngay2Parameter);
        }
    
        public virtual ObjectResult<sp_ThongKeTheoNguoiDung_Result> sp_ThongKeTheoNguoiDung(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeTheoNguoiDung_Result>("sp_ThongKeTheoNguoiDung", tenParameter);
        }
    
        public virtual int sp_ThemNVQuanTri1(string hoTen, Nullable<System.DateTime> ngaySinh, string diaChi, string diaChi2, string sdt, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var diaChi2Parameter = diaChi2 != null ?
                new ObjectParameter("diaChi2", diaChi2) :
                new ObjectParameter("diaChi2", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNVQuanTri1", hoTenParameter, ngaySinhParameter, diaChiParameter, diaChi2Parameter, sdtParameter, emailParameter);
        }
    
        public virtual int sp_ThemTaiKhoanNV1(string ma, string sdt)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoanNV1", maParameter, sdtParameter);
        }
    
        public virtual ObjectResult<sp_XemDanhSachSanPham_KH_Result> sp_XemDanhSachSanPham_KH(string ten_loai)
        {
            var ten_loaiParameter = ten_loai != null ?
                new ObjectParameter("ten_loai", ten_loai) :
                new ObjectParameter("ten_loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDanhSachSanPham_KH_Result>("sp_XemDanhSachSanPham_KH", ten_loaiParameter);
        }
    
        public virtual ObjectResult<sp_XemKhuyenMai_KH_Result> sp_XemKhuyenMai_KH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemKhuyenMai_KH_Result>("sp_XemKhuyenMai_KH");
        }
    }
}
