
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanNuocUong_TheCoffeeShop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NGUOIDUNG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NGUOIDUNG()
    {

        this.PTTHANHTOANs = new HashSet<PTTHANHTOAN>();

    }


    public string USERID { get; set; }

    public string HOTEN { get; set; }

    public string SDT { get; set; }

    public string DIACHI { get; set; }

    public System.DateTime NGAYSINH { get; set; }

    public string EMAIL { get; set; }

    public string DIACHI2 { get; set; }

    public Nullable<int> DIEMTICHLUY { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PTTHANHTOAN> PTTHANHTOANs { get; set; }

    public virtual TAIKHOAN TAIKHOAN { get; set; }

}

}
